# Generated by Django 4.2.4 on 2023-09-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('lead', '0004_alter_lead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='team.team'),
        ),
    ]
